### ISSUE TITLE
¿Donde encuentro el ejemplo de 2D?

### ISSUE THREAD

**Issue by Stephaaniie** [Stephaaniie/algochess#1]
Hola Tomas, buenas tardes!
 Como podría filtrar el ejemplo que me mencionaste ayer que lo iba a encontrar en el foro, filtre por posición y 2d  pero no logro encontrarlo.

**Comment by Stephaaniie** [comment]
Lo encontre!!

**Comment by tomasBustamante** [comment]
https://github.com/fiuba/ProyectoBaseAlgo3/tree/javafx
